export enum ActivityType {
    COMMUNITY_SERVICE = 'COMMUNITY_SERVICE',
    CULTURE_SERVICE = 'CULTURE_SERVICE',
    EMERGENCY_RESCUE = 'EMERGENCY_RESCUE',
    ANIMAL_PROTECTION = 'ANIMAL_PROTECTION',
    POVERTY_ASSISTANCE = 'POVERTY_ASSISTANCE',
    ELDERLY_DISABLED_ASSISTANCE = 'ELDERLY_DISABLED_ASSISTANCE',
    MEDICAL_ASSISTANCE = 'MEDICAL_ASSISTANCE',
    ORPHAN_EDUCATION_ASSISTANCE = 'ORPHAN_EDUCATION_ASSISTANCE'
}